DROP TABLE hvbp_table;

CREATE EXTERNAL TABLE hvbp_table
(
  provider_id string,
  hospital_name string,
  address string,
  city string,
  state string,
  zip string,
  county string,
nurse_floor string,
nurse_achieve_thresh string,
nurse_benchmark string,
nurse_baseline string,
nurse_perf string,
nurse_achieve_pts string,
nurse_improve string,
nurse_dimension string,
doc_floor string,
doc_achieve_thresh string,
doc_benchmark string,
doc_baseline string,
doc_perf string,
doc_achieve_pts string,
doc_improve string,
doc_dimension string,
staff_floor string,
staff_achieve_thresh string,
staff_benchmark string,
staff_baseline string,
staff_perf string,
staff_achieve_pts string,
staff_improve string,
staff_dimesion string,
pain_floor string,
pain_achieve_thresh string,
pain_benchmark string,
pain_baseline string,
pain_perf string,
pain_achieve_pts string,
pain_improve string,
pain_dimension string,
medicine_floor string,
medicine_achieve_thresh string,
medicine_benchmark string,
medicine_baseline string,
medicine_achieve_pts string,
medicine_improve string,
medicine_dimesion string,
environ_floor string,
environ_achieve_thresh string,
environ_benchmark string,
environ_baseline string,
environ_perf string,
environ_achieve_pts string,
environ_improve string,
environ_dimension string,
disharge_floor string,
discharge_achieve_thresh string,
discharge_benchmark string,
discharge_baseline string,
discharge_perf string,
discharge_achieve_pts string,
discharge_improve string,
discharge_dimension string,
overall_floor string,
overall_achieve_thresh string,
overall_benchmark string,
overall_baseline string,
overall_perf string,
overall_achieve_pts string,
overall_improve string,
overall_dimension string,
hcahps_base string,
hcahps_consistency string
)

ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/hospital_compare/hvbp'
;

